User dashboard
Puppy-Playdate/puppy_playdate_fe pull request #13
Opened 2024-01-05 16:01 UTC by bserge13

## Description

Completion of a users dashboard with link to edit, buttons to: log out, add pet, view pets, discover socials; all buttons also have the routes rolled (to be refactored). All testing passes. 

## Type of change
Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Describe testing implemented and what all it covers. 

- [ ]  fully tests happy and sad paths
- [ x] happy path testing only

## Checklist

- [x] code has been self reviewed
- [ x] code runs without any errors
- [x ] all tests pass

### Thanks!

2024-01-05 16:16 UTC, JustinSteel commented on app/views/users/show.html.erb
I think we should we put the log out button in the application view so it is at the top of all the pages.

2024-01-05 16:18 UTC, ttakahashi1591 reviewed
Thanks for getting this all built out and it all looks great. I did notice that coverage files are still being generated in this PR, but I did notice you have it removed on the other PR for the `Draper::Decorator` addition!

2024-01-05 16:18 UTC, JustinSteel commented on spec/features/users/show_spec.rb
looks good!

2024-01-05 16:19 UTC, JustinSteel approved these changes

2024-01-05 18:43 UTC, EricBelongea requested changes

2024-01-05 18:43 UTC, EricBelongea commented on app/views/users/show.html.erb
I'd agree with this. I think Having the Login and Log out is the application view and changing based on whether a user is logged in or not would be a great feature. As well as a dashboard button.

2024-01-05 18:43 UTC, EricBelongea commented on config/routes.rb
> +  get '/users/:id/dogs', to: 'dogs#index', as: :dogs
Yes!

2024-01-06 03:51 UTC, bserge13 commented on app/controllers/users_controller.rb
> +    @user = UserFacade.get_by_id(params[:id])
I don't think the current_user method is working as it should be. All errors for ID conversion when making a poro, array of all users being returned went away went away after reverting back to params[:id]. I might be missing something, but :id is what's being passed in the params within ApplicationController I saw as well

2024-01-06 17:28 UTC, EricBelongea commented
Hey I took this on my local and seems like everything is working? I changed the cassettes and now I have all passing tests. I didn't have to change any code from @bserge13's last PR.

2024-01-06 18:10 UTC, merged